### PR TITLE
Support multiple versions of LibRaw

### PR DESCRIPTION
**Pull request by campaul**
This isn't complete yet but I wanted to get into PR ASAP.

**The way this works**

The user runs `from libraw.bindings import LibRaw`. At import, `libraw.bindings` figures out the version of LibRaw and replaces itself with `libraw.api_10.bindings`. The user is then using the correct version of the `bindings` module.

**How to add a version**

Create a new module `libraw.api_{api_version}` and add the files `bindings.py`, `callbacks.py`, `errors.py`, `structs.py`. The `bindings.py` file should contain a class `LibRaw` that extends `libraw.base.bindings.LibRaw` and implements all the abstract methods.

The function signatures, return types, etc. for your version of LibRaw should be defined in the `__init__` method of your `LibRaw` class. Everything in `callbacks.py`, `errors.py`, and `structs.py` is also expected to change between library versions, so there is no structure to conform to. The user can check the `api_version` property of their `LibRaw` instance to figure out what behavior they should rely on.

### CODE REVIEW

**Comment by campaul** [comment]
Pushed a minor revision that moves the `check_call` behavior out of `libraw.base` because the mechanism could change between versions.

**Comment by SamWhited** [comment]
I was thinking about this PR today, and as much as I hate to say it because I know a lot of work went in to it, I think I've changed my mind about how we should do this.

I am now of the opinion that supporting multiple versions of LibRaw is just going to cause problems, and detract from development and debug time which could be better spent elsewhere. I also don't like messing with imports, even if it does work.

I'm thinking now we should make our major releases correspond to LibRaw major releases (we can have other minor or major releases between LibRaw releases as well) and only support the latest version. If we want to backport fixes to older versions we can, but I don't think it's worth the effort to maintain multiple version support.

Thoughts? I wish I had a better argument for it, but I was just wondering how other libraries delt with this and realized that the answer is mostly just that they don't.

**Comment by campaul** [comment]
The problem is we're technically not a library, we're a binding (or at least this part of the code is). If we only support one version of libraw we'll only be able to support a handful of operating systems. Even right now version 16 isn't enough to cover all supported mainstream linux distributions. Also maintaining two separate versions is inherently non-trivial no matter what git does, so just keeping separate versions of rawkit would be tougher than you're imagining.

**Comment by campaul** [comment]
We can keep the multiple versions of libraw bindings like exist in this branch and just not do the import magic stuff. It will make the code slightly less simple, but I think it's better than just telling anyone on Debian or Ubuntu LTS they can't use our code.

**Comment by campaul** [comment]
Now there is no import magic.

**Comment by campaul** [comment]
If we do go the route of only supporting one version of libraw I don't want to deal with back porting, so old versions would not get new features. That might be OK though if the rawkit part of the api is stable enough. We just don't use any newer features in Photoshell until distros catch up enough to run a newer rawkit.

**Comment by SamWhited** [comment]
Yah, the more I think about it the more I think that makes sense for us (no backports). It just keeps things simple (although, you're right that it makes PhotoShell management a bit harder).

Maybe I'm overthinking it and it's not as much of a problem either way though.

**Pull request closed without merging**
