### PR TITLE
Expose raw data

### LINKED ISSUE #19: Expose raw buffer

### PR DESCRIPTION
**Pull request by campaul**
Fixes #19

### CODE REVIEW

**Comment by paalge** [comment]
Have you tested this on real 3 and 4 colour raw images? Your code assumes that `iwidth` is the same for 3 and 4, colour, which it isn't, and I would expect that you either get a segfault or part of the image . Therefore the addition I made in #104 is slightly different than your `_get_raw`. Except for this the code is good.

**Comment by campaul** [comment]
@paalge nice catch. I'll get this sorted out tonight and add some integration tests to make sure it continues to work in the future.

**Comment by paalge** [comment]
If you need, I can send some test images.

**Comment by campaul** [comment]
@paalge that would be really helpful actually. Or at the very least just knowing a camera model that does each format would be great. If I have model names then I can just pull images from www.rawsamples.ch

**Comment by paalge** [comment]
For the 4 colour I used images from a Nikon D7000 (.NEF)
For the 3 colour I downloaded a x3f file from the Sigma X3F
Test code I used (for 4 colour):
```python
    from rawkit.raw import Raw
    url2 = "DSC_0666.NEF"
    raw = Raw(url2)
    raw.options.bps=16
    raw.unpack()
    import numpy as np
    f,col = raw.get_4_col_raw() 
    f = np.asarray(f)
    import matplotlib.pyplot as plt
    plt.imshow(f[:,:])
    plt.show() 
```

**Comment by campaul** [comment]
Perfect! I'll get this branch all fixed up when I get off work today.

**Comment by campaul** [comment]
After several hours of research and testing and banging my head on the desk I've concluded that this branch is more broken than any of us realized.

First off `iwidth = sizes.width * num_col` doesn't really make sense, because `num_col` is just `len(cdesc)`, which is always 4 no matter what. I'm pretty sure we should have `iwidth = sizes.width * 3` for `color3_image` and `iwidth = sizes.width * 4` for `color4_image`.

Now for the fun part. There are actually 3 places raw data can get allocated. `raw_image`, `color3_image`, and `color4_image`. According to the docs, `raw_image` is used for storing data from cameras with bayer sensors. `color3_image` and `color4_image` are special cases for a handful of cameras that give you direct, non-mosiaced, RGB data. Only one of these three should ever be non-null for a given image. That means if you're trying to get bayer data from the 99% of cameras with that type of sensor (which I think you are), you should be using `raw_image`.

So why did `color4_image` even exist for the images you were working with? This is what I don't understand. Almost every image we tested, both `raw_image` and `color4_image` were non-null, and they both pointed to the same address in memory. This directly contradicts what the documentation says the behavior should be.

Aside from all that, I'm not sure the way we're building the 2D array is correct. It results in 4 side by side images, when I would expect it to show me a single, mosaiced image.

More research is required. I'll continue work on this tonight.

**Comment by paalge** [comment]
Hi

I agree that this is hard.
First of the 4 times for the colour makes sense for the 4 colour images as the width of the image is defined as the interpolated pixels, (For instance the sensor is MxN pixels, thich means there are M/2xN/2=MxN/4 pixels per colour, where M`=iwidth` and N`=iheight`, ..., and then one interpolates these colours for each of the pixels to get an image MxN. 
For the 3 colour there are 3 sensors, one for each colour, each with the size of MxN, meaning that the real image actually is MxN, without any interpolation, though in order to store it, it looks like they add a fourth colour as zero and make the array Mx4xN, making `iwidth=4M`.

I've also noticed that `raw_image` rarely is nonzero, and I never understood what it was for (maybe grayscale images?)

As for the images, my testing gave images as explained in the help text, ie for 4 colour: 
 ```
        R B R B ...
        G B G B ...
        R B R B ...
        . . . . .
        . . . .  .
        . . . .   .
```
and for 3 colour
```
        ---------
        R G B 0 R ...
        R G B 0 R ...
        R G B 0 R ...
        . . . . .
        . . . .  .
        . . . .   .
        --------
```
Which is what one would expect, as this is easily interpolated/moved to a 3D array

**Comment by campaul** [comment]
`raw_image` is for bayer data, and is the *only* field that should be set for 99% of cameras. `color4_image` and `color3_image` are what should be null. The fact that they are populated is probably a bug in libraw (or at the very least undocumented behavior), and using them when `raw_image` exists is technically undefined behavior.

Also the layout you give for 4 color images seems wrong. It has twice the number of blue pixels, but it should have twice the number of green pixels.

**Comment by paalge** [comment]
Ok. I tried reading the docs for `libraw`but found the documentation very different to the real behaviour, which suggests a bug. 
As for the layout, it is defined by the `cdesc` and is different between some models of cameras. But I agree in most cases it is two green and not two blue, though there are other variations with a different blue in on pixel.

**Comment by SamWhited** [comment]
> As for the layout, it is defined by the cdesc and is different between some models of cameras.

They layout is different, but not the length (since it's always one of `RGBG`, `RGBE`, `GMCY`, or `GBTG`.

**Comment by paalge** [comment]
Agreed.

**Comment by campaul** [comment]
Ok, I figured it out. The data you want is `raw_image`, which is stored as single component bayer data. This data is of size `raw_width * raw_height`. It is *not* of size `raw_width * 4 * raw_height` as we were doing. What was actually happening was we were overflowing by doing that. So row 0 of the generated array would actually contain rows 0, 1, 2, and 3 of the raw data, then row 1 would contain rows 1, 2, 3, 4, and so on, until you get to the end and the last images have some rows missing at the bottom.

I still don't know why `color4_image` is non-null, but it shouldn't be used here. It only exists for use with certain Foveon cameras that don't use bayer sensors.

**Comment by campaul** [comment]
I think a lot of confusion I had was about how the mosaiced data worked. I was assuming that the 2x2 RGBG (or RGGB, etc.) block in the raw data corresponded to a single RGB pixel in the demosaiced image. This is incorrect. The 2x2 block corresponds to a 2x2 block in the final image. For clarity and future reference I want to document that here.

**Comment by campaul** [comment]
Did lots of cleanup, tweaking, and rebasing. Now the APIs have changed a little but I've verified everything works as expected across several different raw images. The code looks something like:

```python
from rawkit import Raw
from scipy import misc

with Raw('some_file.CR2') as raw:
    data = raw.bayer_data(include_margin=True)  # include_margin defaults to False
    cdesc = raw.color_description  # if you need it

    if data:
        # display the raw bayer data as an image
        misc.toimage(data).show()
```

The reason I broke color description out into its own property is because the previous code encouraged writing a line like `data, cdesc = raw.bayer_data()`, which will crash if `bayer_data` returns None.

**Comment by campaul** [comment]
Correction: now I have rebased everything correctly.

**Comment by paalge** [comment]
It looks good now, though I still feel that including the cdesc is advantageous, as it is necessary to understand the data. But the description shows how to get it at least.

**Comment by campaul** [comment]
That was totally a trade off. `cdesc` belongs with the bayer data, but at the same time people expect a function that returns a tuple to always be unpackable. I did at least try to make it as accessible as possible though, so hopefully this isn't too annoying to use.

**Comment by campaul** [comment]
Ok, I went back and changed `bayer_data` to `raw_image`, and made a new `bayer_data` function that returns a tuple of `raw_image` and `color_description`.

I also changed `raw_data` to return an empty list instead of `None` so you can throw the result straight into a for loop without worrying about None errors. Empty lists are falsy so code that does `if data:` will still work fine.

**Comment by campaul** [comment]
Sorry for going through so many revisions with this. I'm really happy with the current state of things, so if @paalge signs off I'll merge.

**Comment by SamWhited** [comment]
:shipit:

**Comment by KelSolaar** [comment]
Loosely lurking on that, do you have an up to date minimal example on how the new objects work (bayer data & pattern)? Something like that?

```python
from rawkit import Raw
from scipy import misc

with Raw('some_file.CR2') as raw:
    data, cdesc = raw.bayer_data(include_margin=False)
```

I assume `data` is the bayer data in the form of a 2d array? and `cdesc `?

**Comment by KelSolaar** [comment]
By the way, we have some demosaicing code available here: https://github.com/colour-science/colour-demosaicing/

**Comment by campaul** [comment]
`data` is a 2D array formatted as a list of rows. `cdesc` is a string like `RGGB`. I don't have usage examples yet but the return format is in the doc strings.

**Comment by KelSolaar** [comment]
That's perfect, I should be able to feed that directly!

**Comment by paalge** [comment]
This is a nice solution. I haven't tested it on any image, but if you've done it. I'm good with this

**Comment by KelSolaar** [comment]
I pulled the code and the PR, did `python setup.py install` but it looks like I'm missing all the objets:

```bash
(colour-2.7)Lilith:rawkit kelsolaar$ python
Python 2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import rawkit
>>> dir(rawkit)
['VERSION', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']
>>> 
```

How do you proceed to build / test that?

**Comment by SamWhited** [comment]
That's just how Python works, you'll have to import the things you want to use:

```python
>>> import rawkit
>>> dir(rawkit)
['VERSION', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> from rawkit.raw import Raw
>>> dir(rawkit)
['VERSION', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'errors', 'metadata', 'options', 'raw']
>>> 
```

**Comment by KelSolaar** [comment]
Nothing prevents you to have the `Raw` class imported at the base package level (which would make sense), I haven't checked that particularly. Anyway:

```bash
(colour-2.7)Lilith:rawkit-0.4.3 kelsolaar$ python
Python 2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import rawkit
>>> from rawkit import Raw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Raw
>>> 
```

**Comment by campaul** [comment]
Sorry, I made a mistake in my example. `from rawkit.raw import Raw` is the correct line.

**Comment by KelSolaar** [comment]
@campaul Much better, no more import error, however I have a cryptic exception while loading a CR2 file. Can I can confirm if *libraw* has been properly binded, I have *libraw-0.17.0* installed at the moment.

```python
>>> from rawkit.raw import Raw
>>> 
>>> IMAGE = '/Users/kelsolaar/Documents/Development/colour-science/colour-hdri/colour_hdri/resources/colour-hdri-tests-dataset/IMG_2601.CR2'
>>> 
>>> with Raw(IMAGE) as raw:
...     data, cdesc = raw.bayer_data(include_margin=False)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rawkit/raw.py", line 72, in __init__
    self.libraw.libraw_open_file(self.data, filename.encode('ascii'))
  File "libraw/errors.py", line 121, in check_call
    raise_if_error(exit_code.value)
  File "libraw/errors.py", line 141, in raise_if_error
    }[error_code]
IOError
>>> 
```

**Comment by campaul** [comment]
@KelSolaar we haven't gotten support for 0.17 yet, right now we require 0.16. But support for 0.17 is coming soon.

**Comment by KelSolaar** [comment]
I saw that in the docs but wasn't sure it was still current, I'll get that installed and give it another go.

**Comment by KelSolaar** [comment]
I managed to load my first image with *libraw-0.17.0*, however I need to double check and it could be on my side but there is "maybe" an issue in the way the CFA mask is returned on my tests images I'm expecting *RGBG*  but I receive * RGBG*.

I'll investigate further and will open an issue accordingly.

**Comment by SamWhited** [comment]
@KelSolaar This appears to work fine for me; we're just grabbing the value LibRaw gives us either way, so if it's a bug it would be upstream.

**Comment by KelSolaar** [comment]
It could be related on how *libraw* returns the CFA mask pattern. On this image: https://github.com/colour-science/colour-hdri-tests-dataset/blob/master/frobisher_001/IMG_2602.CR2

I should have a CFA mask pattern as follow: *RGGB*

```
R G
G B
```

image

It looks like *libraw* is returning the pattern in a clock-wise order instead of per row basis.

**Comment by SamWhited** [comment]
That's correct; it's returning the pattern of a beyer sensel (the 2x2 grid). Sorry, I was actually misunderstanding your question; I thought you meant there was a space in the string :)

**Comment by KelSolaar** [comment]
Yeah but I'm not sure what is the order of it and their docs on `cdesc` don't provide any more answers: http://www.libraw.org/docs/API-datastruct-eng.html

> char cdesc[5];
Description of colors numbered from 0 to 3 (RGBG,RGBE,GMCY, or GBTG).

From the look of it (and using my data as comparison basis) they return the CFA pattern in a clock-wise order:

```
1 2
4 3
```

instead of per row:

```
1 2
3 4
```

I'll ask them confirmation for that.

**Comment by SamWhited** [comment]
Yah, this is definitely returning different results than dcraw. Will advise.

**Comment by KelSolaar** [comment]
I opened a related thread a while back on their forum, I just replied asking for the above: http://www.libraw.org/node/2137

**Comment by SamWhited** [comment]
Glancing at the code and docs, I don't think cdesc is supposed to return information about the order of the colors at all; just about what colors are there, which actually makes sense.

**Comment by campaul** [comment]
@KelSolaar check out https://github.com/photoshell/rawkit/issues/113. `cdesc` doesn't tell you the order of the pixels, only what colors are there.

**Comment by KelSolaar** [comment]
Yeah I just saw, thanks! I haven't dived too much in *libraw* yet as I'm mainly using *dcraw* for my stuff.

**Pull request merged**
