### PR TITLE
Remove IRC info since we never idle there anymore

### PR DESCRIPTION
**Pull request by SamWhited**
Probably best not to advertise this since as far as I know neither of us idle there anymore.

### CODE REVIEW

**Comment by campaul** [comment]
Should we put something about opening tickets instead? We're actually pretty good about responding to those.

**Comment by SamWhited** [comment]
Do we? Took us ages to get the LibRaw 18 code merged since neither of us wanted to test it. Maybe we should just mark it as unmaintained and hope someone else comes along who's interested in this sort of thing and doesn't mind dealing with Python.

**Comment by campaul** [comment]
It only took us ages because we were witing on distros to add libraw 0.18. Once someone specifically asked for an upgrade to version 0.18 we had it shipped in 5 days. I'm actually keeping things maintained as people ask for them (and going through the backlog of issues now).

**Comment by SamWhited** [comment]
We can if you want then; I'll merge this for now and more text can be added later.

**Pull request merged**
